[project]
name = "inria_academy"
version = "0.1.0"
description = "Training on advanced signal processing tools"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "scipy>=1.17.1",
    "EMD-signal==1.9.0",
    "PyWavelets==1.8.0",
    "ssqueezepy==0.6.6",
    "vmdpy",
    "neurokit2>=0.2.10",
]

[project.optional-dependencies]
dev = [
    "pytest", "ruff",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-gallery",
    "pymdown-extensions",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
    "mkdocs-gallery",
    "pdoc>=16.0.0",
]
